version: '3'
services:
  queue:
    image: rabbitmq:3-management
    ports:
      - '5672:5672'
      - '15672:15672'
  app:
    image: node:8.9-alpine
    entrypoint: /bin/sh
    volumes:
      - '.:/home/ec2user'
    ports:
      - '8000:3000'
    tty: true
    depends_on:
      - queue